"""empty message

Revision ID: 15d59eb0993
Revises: None
Create Date: 2014-05-25 13:15:20.361473

"""

# revision identifiers, used by Alembic.
revision = '15d59eb0993'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('superuniversum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superuniversum_id'], ['universum.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('superaspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superaspect_id'], ['aspect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aspects',
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.Column('universum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['universum_id'], ['universum.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aspects')
    op.drop_table('aspect')
    op.drop_table('universum')
    ### end Alembic commands ###
