"""Initial commit

Revision ID: 1daababb8b8
Revises: None
Create Date: 2014-06-15 23:27:24.100012

"""

# revision identifiers, used by Alembic.
revision = '1daababb8b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('superaspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['superaspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('universum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('superuniversum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['superuniversum_id'], ['universum.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('universum_aspect',
    sa.Column('universum_id', sa.Integer(), nullable=True),
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['universum_id'], ['universum.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universum_aspect')
    op.drop_table('dimension')
    op.drop_table('universum')
    op.drop_table('aspect')
    op.drop_table('level')
    op.drop_table('table')
    ### end Alembic commands ###
