"""Added dimension type

Revision ID: 2555cbeaa87
Revises: 2997dcbd8d3
Create Date: 2014-06-18 19:11:22.725307

"""

# revision identifiers, used by Alembic.
revision = '2555cbeaa87'
down_revision = '2997dcbd8d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension', sa.Column('type', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension', 'type')
    ### end Alembic commands ###
