"""Added table model

Revision ID: 44a491c7e59
Revises: 5005b5114d3
Create Date: 2014-06-13 15:01:02.591854

"""

# revision identifiers, used by Alembic.
revision = '44a491c7e59'
down_revision = '5005b5114d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('aspect', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('dimension', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('universum', sa.Column('table_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universum', 'table_id')
    op.drop_column('dimension', 'table_id')
    op.drop_column('aspect', 'table_id')
    op.drop_table('table')
    ### end Alembic commands ###
