"""Added level model

Revision ID: 51ad04a4577
Revises: 44a491c7e59
Create Date: 2014-06-14 14:06:09.546860

"""

# revision identifiers, used by Alembic.
revision = '51ad04a4577'
down_revision = '44a491c7e59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('table_level',
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_level')
    op.drop_table('level')
    ### end Alembic commands ###
