"""Added level model

Revision ID: c34765c0f0
Revises: 51ad04a4577
Create Date: 2014-06-14 14:09:43.775709

"""

# revision identifiers, used by Alembic.
revision = 'c34765c0f0'
down_revision = '51ad04a4577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('universum', sa.Column('level_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universum', 'level_id')
    op.drop_column('aspect', 'level_id')
    ### end Alembic commands ###
